name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Add permissions block
permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Node.js for npm
      uses: actions/setup-node@v4
      with:
        node-version: '22.10.0'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run linting
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Publish to npm
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release

    - name: Setup Node.js for GitHub Packages
      uses: actions/setup-node@v4
      with:
        node-version: '22.10.0'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@nginh'

    - name: Publish to GitHub Packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        echo "@nginh:registry=https://npm.pkg.github.com" >> .npmrc
        npm publish --registry=https://npm.pkg.github.com 